name: renovatePG
on:
 workflow_dispatch:
permissions: write-all
jobs:
  renovate:
    runs-on: default
    steps:
      - name: Test 1
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Test 2
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
      - name: Test 3
        uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3.0.0
