name: renovatePG
on:
 workflow_dispatch:
permissions: write-all
jobs:
  renovate:
    runs-on: default
    steps:
      - name: Test 1
        uses: actions/checkout@v3
      - name: Test 2
        uses: actions/setup-go@v4
      - name: Test 3
        uses: hashicorp/vault-action@v3.0.0
