name: renovatePG
on:
 workflow_dispatch:
jobs:
  renovate:
    runs-on: default
    steps:
      - name: Test 1
        uses: actions/checkout@v4
      - name: Test 2
        uses: actions/setup-go@v3
