name: renovatePG
on:
 workflow_dispatch:
jobs:
  renovate:
    runs-on: default
    steps:
      - name: Test 1
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Test 2
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
