name: renovatePG

on:
 workflow_dispatch:

jobs:
  renovate:
    runs-on: default
    steps:
      - name: Test 1
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Test 2
        uses: actions/setup-go@v4
